---
- name: Install Letsencrypt
  apt:
    name: letsencrypt
    state: present

- name: Generate certificates
  command: "letsencrypt --standalone --email {{ admin_email }} --agree-tos{% for name in domains %} -d {{name}}{% endfor %} certonly"
  args:
    creates: "/etc/letsencrypt/live/*"
  register: certgen
  when: gen_certificates

- name: Set up cron job
  template:
    src: "letsencrypt"
    dest: "/etc/cron.weekly/letsencrypt"
    mode: 0755
  when: gen_certificates
