# Generated by Django 5.1.2 on 2024-11-04 22:19

import django.db.models.deletion
import django_otp.plugins.otp_email.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    replaces = [
        ("tg_bot", "0001_initial"),
        ("tg_bot", "0002_auto_20180727_1817"),
        ("tg_bot", "0003_telegramdevice"),
        ("tg_bot", "0004_auto_20190725_2023"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.",
                        max_length=64,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=django_otp.plugins.otp_email.models.default_key,
                        help_text="A hex-encoded secret key of up to 20 bytes.",
                        max_length=80,
                        validators=[django_otp.plugins.otp_email.models.key_validator],
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False, help_text="Is this device ready for use?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that this device belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
