# Generated by Django 2.0.7 on 2018-07-27 18:17

from django.db import migrations

# Undo a mistake with the superclass. Thankfully we never really did this yet in production.


class Migration(migrations.Migration):
    dependencies = [
        ("tg_bot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramDevice",
        ),
    ]
