---
- name: postmap
  command: "postmap /etc/postfix/header_checks"

- name: restart postfix
  command: "/etc/init.d/postfix restart"

- name: restart opendkim
  command: "/etc/init.d/opendkim restart"
