# Generated by Django 5.1.2 on 2024-11-13 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallink",
            options={"ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="sociallink",
            name="url",
            field=models.URLField(
                default="https://example.com/",
                help_text="URL of account on site.",
                validators=[django.core.validators.URLValidator(schemes=("https",))],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="comment",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short comment, such as 'Cat Photo Account'.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="identifier",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Username on this site.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="site_name",
            field=models.CharField(
                db_index=True,
                help_text="The name of the site your account is on.",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="socialsettings",
            name="promotion_notes",
            field=models.TextField(
                blank=True,
                help_text="Any notes/requests/conditions on using your content in promotions.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="socialsettings",
            name="quick_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A quick description of your art/style/offerings, for use by our social media specialist when promoting you.",
                max_length=150,
            ),
        ),
    ]
