# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_auto_20180115_1537"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageasset",
            name="artist",
        ),
        migrations.AddField(
            model_name="imageasset",
            name="artist",
            field=models.ManyToManyField(
                blank=True, related_name="art", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
