# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_primary_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageasset',
            options={'ordering': ('created_on',)},
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
