# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171212_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='comments_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='primary_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.ImageAsset'),
        ),
    ]
