# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180118_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
