# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20180102_2215'),
        ('profiles', '0006_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='sales.Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Clean/Safe for work'), (1, 'Risque/mature, not adult content but not safe for work'), (2, 'Adult content, not safe for work'), (3, 'Offensive/Disturbing to most viewers, not safe for work')]),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Clean/Safe for work'), (1, 'Risque/mature, not adult content but not safe for work'), (2, 'Adult content, not safe for work'), (3, 'Offensive/Disturbing to most viewers, not safe for work')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Clean/Safe for work'), (1, 'Risque/mature, not adult content but not safe for work'), (2, 'Adult content, not safe for work'), (3, 'Offensive/Disturbing to most viewers, not safe for work')], db_index=True, default=0, help_text='Shows the maximum rating to display. By setting this to anything other than general, you certify that you are of legal age to view adult content in your country.'),
        ),
    ]
