# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_remove_imageasset_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageasset",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="assets", to="profiles.Tag"
            ),
        ),
    ]
