# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_imageasset_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="tags",
            field=models.ManyToManyField(to="profiles.Tag"),
        ),
    ]
