# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_auto_20180125_1524"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
