# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 16:45
from __future__ import unicode_literals

from django.db import migrations
from rest_framework.authtoken.models import Token


def gen_tokens(apps, schema):
    user_cls = apps.get_model('profiles.User')
    for user in user_cls.objects.all():
        Token.objects.get_or_create(user_id=user.id)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180125_1524'),
    ]

    operations = [
        migrations.RunPython(gen_tokens, lambda x, y: None)
    ]
