# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_auto_20180126_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blacklist",
            field=models.ManyToManyField(blank=True, to="lib.Tag"),
        ),
        migrations.AlterField(
            model_name="character",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="lib.Tag"
            ),
        ),
        migrations.AlterField(
            model_name="imageasset",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="assets", to="lib.Tag"
            ),
        ),
    ]
