# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 21:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_auto_20180131_1747"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refcolor",
            name="name",
        ),
        migrations.AlterField(
            model_name="refcolor",
            name="color",
            field=models.CharField(
                max_length=6,
                validators=[django.core.validators.RegexValidator("^[0-9a-f]{6}$")],
            ),
        ),
    ]
