# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_auto_20180201_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.CharField(blank=True, default="", max_length=5000),
        ),
    ]
