# Generated by Django 2.0.3 on 2018-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0018_auto_20180322_1643"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="favorites_hidden",
        ),
        migrations.AddField(
            model_name="user",
            name="favorites_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
