# Generated by Django 2.0.3 on 2018-03-27 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0021_auto_20180327_1734"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="character",
            name="species",
        ),
    ]
