# Generated by Django 2.0.3 on 2018-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0022_auto_20180327_1900"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="load",
            field=models.IntegerField(default=0),
        ),
    ]
