# Generated by Django 2.0.3 on 2018-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0024_character_taggable"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="taggable",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
