# Generated by Django 2.0.3 on 2018-04-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_user_taggable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50)),
                ('value', models.CharField(default='', max_length=100)),
                ('sticky', models.BooleanField(db_index=True, default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='profiles.Character')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('key', 'character')},
        ),
    ]
