# Generated by Django 2.0.3 on 2018-04-05 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0026_auto_20180404_1925"),
    ]

    operations = [
        migrations.RenameField("ImageAsset", "uploaded_by", "owner"),
    ]
