# Generated by Django 2.0.3 on 2018-04-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0027_auto_20180405_1952"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="imageasset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_profiles_imageasset",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
