# Generated by Django 2.0.3 on 2018-04-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0016_charactertransfer"),
        ("profiles", "0028_auto_20180405_1954"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sales.CharacterTransfer",
            ),
        ),
    ]
