# Generated by Django 2.0.4 on 2018-04-24 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_character_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
