# Generated by Django 2.0.4 on 2018-04-25 16:26
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0030_auto_20180424_1832"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
