# Generated by Django 2.0.4 on 2018-04-30 15:25

from django.db import migrations


CHAR_SHARED = 24


def add_share_subscriptions(apps, schema):
    User = apps.get_model('profiles', 'User')
    Subscription = apps.get_model('lib', 'Subscription')
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type = ContentType.objects.get(app_label='profiles', model='user')
    # Remove previously erroneous character share subscriptions.
    Subscription.objects.filter(type=CHAR_SHARED).delete()
    for user in User.objects.all():
        Subscription.objects.get_or_create(
            subscriber=user,
            content_type=content_type,
            object_id=user.id,
            type=CHAR_SHARED
        )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20180425_1626'),
    ]

    operations = [
        migrations.RunPython(add_share_subscriptions, reverse_code=lambda x, y: None)
    ]
