# Generated by Django 2.0.4 on 2018-04-30 15:25
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0031_auto_20180425_1626"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
