# Generated by Django 2.0.4 on 2018-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0033_user_watching"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="commissions_disabled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Internal check for commissions that prevents taking on more work when max load is exceeded.",
            ),
        ),
    ]
