# Generated by Django 2.0.4 on 2018-05-16 19:26

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0036_user_blocking"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="last_activity",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="sender_read",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="received_messages",
                through="profiles.MessageRecipientRelationship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
