# Generated by Django 2.0.4 on 2018-05-21 22:02
from apps.lib.constants import STREAMING
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0038_user_commission_info"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
