# Generated by Django 2.0.4 on 2018-06-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_rating_created_on'),
        ('profiles', '0042_auto_20180612_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.CreditCardToken'),
        ),
    ]
