# Generated by Django 2.0.6 on 2018-06-21 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0042_auto_20180612_2023"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
