# Generated by Django 2.0.7 on 2018-07-13 20:19
from apps.lib.constants import NEW_JOURNAL
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0047_journal"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
