# Generated by Django 2.0.7 on 2018-07-18 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0048_auto_20180713_2019"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
