# Generated by Django 2.0.7 on 2018-07-19 21:28
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0049_auto_20180718_1754"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
