# Generated by Django 2.0.7 on 2018-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0051_remove_user_use_load_tracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auto_withdraw",
            field=models.BooleanField(default=True),
        ),
    ]
