# Generated by Django 2.0.7 on 2018-08-16 21:12
from apps.lib.constants import TRANSFER_FAILED
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0052_user_auto_withdraw"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
