# Generated by Django 2.0.7 on 2018-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20180816_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='escrow_disabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
