# Generated by Django 2.0.8 on 2018-09-17 23:55
from apps.lib.constants import SUBMISSION_ARTIST_TAG
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0054_user_escrow_disabled"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
