# Generated by Django 2.0.8 on 2018-09-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_auto_20180917_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stars',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
