# Generated by Django 2.0.8 on 2018-09-19 19:33

from django.db import migrations

from apps.sales.utils import update_availability


def set_has_products(apps, schema):
    # Broken migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_user_has_products'),
    ]

    operations = [
        migrations.RunPython(set_has_products, lambda x, y: None)
    ]
