# Generated by Django 2.0.8 on 2018-09-19 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0057_user_has_products"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
