# Generated by Django 2.0.8 on 2018-09-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0058_auto_20180919_1933"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True),
        ),
    ]
