# Generated by Django 2.0.7 on 2018-10-01 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0062_auto_20180929_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
