# Generated by Django 2.0.8 on 2018-10-03 15:32
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0064_auto_20181003_1501"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
