# Generated by Django 2.0.8 on 2018-10-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0065_auto_20181003_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offered_mailchimp',
            field=models.BooleanField(default=False),
        ),
    ]
