# Generated by Django 2.0.8 on 2018-10-03 19:39

from django.db import migrations


# This migration has been nullified
class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0066_user_offered_mailchimp"),
    ]

    operations = []
