# Generated by Django 2.1.5 on 2019-02-03 18:20

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0067_auto_20181003_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='art/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ACC', 'AE', 'AI', 'AN', 'AVI', 'BMP', 'DGN', 'DOC', 'DOCH', 'DOCM', 'DOCX', 'DOTH', 'DW', 'DWFX', 'DWG', 'DXF', 'EPS', 'F4A', 'F4V', 'FLV', 'FS', 'GIF', 'IND', 'JPEG', 'JPG', 'JPP', 'LR', 'M4V', 'MIDI', 'MKV', 'MOV', 'MP3', 'MP4', 'MPEG', 'MPG', 'OGA', 'OGG', 'OGV', 'PDF', 'PNG', 'PS', 'PSD', 'RTF', 'SVG', 'SWF', 'TIF', 'TIFF', 'TXT', 'VTX', 'WAV', 'WDP', 'WEBM', 'WMA', 'WMV', 'ZIP'))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account_status',
            field=models.IntegerField(blank=True, choices=[(None, 'Unset'), (1, 'Has US Bank account'), (2, 'No US Bank account')], db_index=True, default=None, null=True),
        ),
    ]
