# Generated by Django 2.1.5 on 2019-07-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0070_message_edited'),
    ]

    run_before = [
        ('sales', '0043_auto_20190701_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='transfer',
        ),
    ]
