# Generated by Django 2.2.1 on 2019-06-10 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0077_artistprofile"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
