# Generated by Django 2.2.1 on 2019-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0079_auto_20190610_1836"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="artist_mode",
            field=models.BooleanField(
                db_index=True,
                default=None,
                null=True,
                blank=True,
                help_text="Enable Artist functionality",
            ),
        ),
    ]
