# Generated by Django 2.2.1 on 2019-06-11 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0080_user_artist_mode"),
        ("sales", "0048_auto_20190610_1837"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
