# Generated by Django 2.2.1 on 2019-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0081_set_artist_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="max_rating",
            field=models.IntegerField(
                choices=[
                    (0, "Clean/Safe for work"),
                    (1, "Risque/mature, not adult content but not safe for work"),
                    (2, "Adult content, not safe for work"),
                    (3, "Offensive/Disturbing to most viewers, not safe for work"),
                ],
                db_index=True,
                default=0,
                help_text="The maximum content rating you are willing to create.",
            ),
        ),
    ]
