# Generated by Django 2.2.1 on 2019-06-11 18:42

from django.db import migrations
from django.db.models import Max


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0082_artistprofile_max_rating"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
