# Generated by Django 2.2.1 on 2019-07-01 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0083_set_max_rating"),
        ("profiles", "0071_remove_character_transfer"),
    ]

    operations = []
