# Generated by Django 2.2.1 on 2019-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0084_merge_20190701_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
