# Generated by Django 2.2.1 on 2019-07-10 18:08
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0086_message_to_conversation"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
