# Generated by Django 2.2.1 on 2019-07-25 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0024_auto_20190725_2023"),
        ("profiles", "0088_conversation_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lib.Asset",
                related_name="full_%(app_label)s_%(class)s",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="preview_asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lib.Asset",
                related_name="preview_%(app_label)s_%(class)s",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_on",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
