# Generated by Django 2.2.1 on 2019-10-10 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0090_auto_20190725_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auto_withdraw',
        ),
        migrations.AlterField(
            model_name='refcolor',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_old',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='art/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ACC', 'AE', 'AI', 'AN', 'AVI', 'BMP', 'DGN', 'DOC', 'DOCH', 'DOCM', 'DOCX', 'DOTH', 'DW', 'DWFX', 'DWG', 'DXF', 'EPS', 'F4A', 'F4V', 'FLV', 'FS', 'GIF', 'IND', 'JPEG', 'JPG', 'JPP', 'LR', 'M4V', 'MIDI', 'MKV', 'MOV', 'MP3', 'MP4', 'MPEG', 'MPG', 'OGA', 'OGG', 'OGV', 'PDF', 'PNG', 'PS', 'PSD', 'RTF', 'SVG', 'SWF', 'TIF', 'TIFF', 'TXT', 'VTX', 'WAV', 'WDP', 'WEBM', 'WMA', 'WMV', 'ZIP'))]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_profiles_submission', to='lib.Asset'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='profiles.Submission'),
        ),
    ]
