# Generated by Django 2.2.1 on 2019-11-29 22:54
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0093_auto_20191119_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_activity",
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
