# Generated by Django 3.0.4 on 2020-03-17 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0027_auto_20191125_1734'),
        ('profiles', '0096_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailchimp_id',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_profiles_submission', to='lib.Asset'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_profiles_submission', to=settings.AUTH_USER_MODEL),
        ),
    ]
