# Generated by Django 3.0.6 on 2020-06-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0098_auto_20200605_1051'),
        ('profiles', '0100_remove_submission_order'),
    ]

    operations = [
    ]
