# Generated by Django 3.0.6 on 2020-07-11 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0102_user_rating_count"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
