# Generated by Django 3.0.6 on 2020-07-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0103_auto_20200711_0959"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(db_index=True, default=None, null=True),
        ),
    ]
