# Generated by Django 3.0.11 on 2020-12-30 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0104_user_birthday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="file_old",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="preview_old",
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^/\\\\?%&+#]+$",
                        message="Names may not contain /, \\, ?, #, or &.",
                    ),
                    django.core.validators.RegexValidator(
                        "^[^.]", message="Names may not start with a period."
                    ),
                    django.core.validators.RegexValidator(
                        "[^.]$", message="Names may not end with a period."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="primary_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.Submission",
            ),
        ),
    ]
