# Generated by Django 3.1.13 on 2021-07-28 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0105_auto_20201230_1041"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
