# Generated by Django 3.1.13 on 2021-07-28 17:54

from django.db import migrations

WAITLIST_UPDATED = 36


def update_email_setting(apps, value: bool):
    Subscription = apps.get_model("lib", "Subscription")
    Subscription.objects.filter(type=WAITLIST_UPDATED).update(email=value)


enable_emails = lambda apps, schema: update_email_setting(apps, True)
disable_emails = lambda apps, schema: update_email_setting(apps, False)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0105_auto_20201230_1041"),
    ]

    operations = [migrations.RunPython(enable_emails, reverse_code=disable_emails)]
