# Generated by Django 3.2.6 on 2021-08-20 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0106_subscribe_waitlist_emails"),
        ("profiles", "0107_user_current_intent"),
    ]

    operations = []
