# Generated by Django 3.2.6 on 2021-09-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0110_alter_user_processor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='processor',
        ),
    ]
