# Generated by Django 3.2.9 on 2021-12-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0114_remove_portrait"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="sales.revision",
            ),
        ),
    ]
