# Generated by Django 3.2.9 on 2021-12-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0123_remove_transactionrecord_remote_id'),
        ('profiles', '0114_remove_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='sales.revision'),
        ),
    ]
