# Generated by Django 3.2.9 on 2021-12-11 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0115_submission_revision"),
        ("sales", "0123_remove_transactionrecord_remote_id"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
