# Generated by Django 3.2.9 on 2021-12-11 13:29

from django.db import migrations


def migrate_revisions(apps, schema):
    Submission = apps.get_model('profiles', 'Submission')
    for submission in Submission.objects.exclude(deliverable=None):
        submission.revision = submission.deliverable.revisions.last()
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0115_submission_revision'),
    ]

    operations = [
        migrations.RunPython(migrate_revisions, reverse_code=lambda x, y: None)
    ]
