# Generated by Django 3.2.9 on 2021-12-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0116_migrate_submission_order_inputs'),
        ('sales', '0125_set_initial_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='max_rating',
        ),
    ]
