# Generated by Django 3.2.9 on 2022-02-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0129_service_plan'),
        ('profiles', '0117_remove_artistprofile_max_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='sales.serviceplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='next_service_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_users', to='sales.serviceplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='service_plan_paid_through',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
