# Generated by Django 3.2.13 on 2022-05-07 09:14

from django.db import migrations


def create_tags(apps, schema):
    ArtistTag = apps.get_model('profiles', 'ArtistTag')
    Submission = apps.get_model('profiles', 'Submission')
    position_tag = 0
    for tag in Submission.artists.through.objects.all().order_by('submission__created_on'):
        ArtistTag.objects.get_or_create(user=tag.user, submission=tag.submission, display_position=position_tag)
        position_tag += 1
    position_submission = 0
    for submission in Submission.objects.order_by('created_on'):
        submission.display_position = position_submission
        submission.save()
        position_submission += 1


def transpose_tags(apps, schema):
    ArtistTag = apps.get_model('profiles', 'ArtistTag')
    for tag in ArtistTag.objects.all():
        tag.submission.artists.add(tag.user)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0120_auto_20220507_0409'),
    ]

    operations = [
        migrations.RunPython(create_tags, reverse_code=transpose_tags)
    ]
