# Generated by Django 3.2.13 on 2022-05-07 09:14

from apps.profiles.models import (
    get_next_artist_position,
    get_next_character_position,
    get_next_submission_position,
)
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0120_auto_20220507_0409"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
