# Generated by Django 3.2.13 on 2022-06-04 01:13

from django.db import migrations
from django.db.models import F


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0123_auto_20220507_0643"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
