# Generated by Django 3.2.15 on 2022-10-30 22:37
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0124_auto_20220603_2013"),
        ("lib", "0037_auto_20221030_1740"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
