# Generated by Django 3.2.15 on 2022-11-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0125_auto_20220930_0941'),
        ('profiles', '0125_correct_profile_hitcount'),
    ]

    operations = [
    ]
