# Generated by Django 4.1.5 on 2023-01-25 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0038_alter_tag_name'),
        ('profiles', '0127_user_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trust_level',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='escrow_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
