# Generated by Django 4.1.5 on 2023-01-24 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0038_alter_tag_name'),
        ('profiles', '0127_user_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trust_level',
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='bank_account_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unset'), (1, 'Included in all sales'), (2, 'Disabled'), (3, 'Shield enabled by default, allow customers to disable it.'), (4, 'Shield disabled by default, allow customers to upgrade to it')], db_index=True, default=0),
        ),
        migrations.RenameField(
            model_name='artistprofile',
            old_name='bank_account_status',
            new_name='shield_option',
        ),
    ]
