# Generated by Django 4.1.5 on 2023-01-25 20:35

from django.db import migrations
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0128_remove_user_trust_level_artistprofile_escrow_enabled"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
