# Generated by Django 4.1.5 on 2023-01-25 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0038_alter_tag_name"),
        ("profiles", "0129_flip_escrow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artistprofile",
            name="escrow_disabled",
        ),
    ]
