# Generated by Django 4.1.7 on 2023-02-24 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0130_remove_artistprofile_escrow_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_email",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="delinquent",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
