# Generated by Django 4.2 on 2023-04-15 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0041_note"),
        ("profiles", "0131_user_verified_email_and_delinquent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistprofile",
            name="commission_info",
            field=models.CharField(blank=True, default="", max_length=14000),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="full_%(app_label)s_%(class)s",
                to="lib.asset",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="preview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preview_%(app_label)s_%(class)s",
                to="lib.asset",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="delinquent",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Enabled when a user's account is in arrears beyond the "
                "grace period.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
