# Generated by Django 4.2 on 2023-05-13 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0133_favorite_user_new_favorites"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
