# Generated by Django 4.2 on 2023-05-13 20:13

from django.db import migrations


def populate_favorites(apps, schema_editor):
    User = apps.get_model("profiles", "User")
    Favorite = apps.get_model("profiles", "Favorite")
    for old_favorite in User.favorites.through.objects.all():
        Favorite.objects.get_or_create(user=old_favorite.user, submission=old_favorite.submission)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0133_favorite_user_new_favorites"),
    ]

    operations = [migrations.RunPython(populate_favorites, reverse_code=migrations.RunPython.noop)]
