# Generated by Django 4.2 on 2023-05-13 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0134_populate_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="favorites",
            new_name="old_favorites",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="new_favorites",
            new_name="favorites",
        ),
    ]
