# Generated by Django 4.2.1 on 2023-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0135_rename_favorites_user_old_favorites"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ("-created_on",)},
        ),
        migrations.RemoveField(
            model_name="user",
            name="old_favorites",
        ),
        migrations.AddField(
            model_name="user",
            name="drip_id",
            field=models.CharField(db_index=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorites",
                through="profiles.Favorite",
                to="profiles.submission",
            ),
        ),
    ]
