# Generated by Django 4.2.1 on 2023-06-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0136_alter_favorite_options_remove_user_old_favorites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="nsfw",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Used to indicate that this character should not be shown when in SFW mode, and its tags should be excluded based on a user's NSFW blocked tags.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nsfw_blacklist",
            field=models.ManyToManyField(
                related_name="nsfw_blacklisting_users", to="lib.tag"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="blacklist",
            field=models.ManyToManyField(
                blank=True, related_name="blacklisting_users", to="lib.tag"
            ),
        ),
    ]
