# Generated by Django 4.2.10 on 2024-02-28 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0137_nsfw_blocked_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_nulled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^/\\\\?%&+#@]+$",
                        message="Names may not contain /, \\, ?, #, @, or &.",
                    ),
                    django.core.validators.RegexValidator(
                        "^[^.]", message="Names may not start with a period."
                    ),
                    django.core.validators.RegexValidator(
                        "[^.]$", message="Names may not end with a period."
                    ),
                ],
            ),
        ),
    ]
