# Generated by Django 4.2.10 on 2024-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0139_alter_character_options_alter_journal_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_adult",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
