# Generated by Django 4.2.11 on 2024-04-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0140_add_verified_adult"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
