# Generated by Django 4.2.11 on 2024-04-09 21:42

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0141_force_reset_display_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisttag",
            name="display_position",
            field=models.FloatField(
                db_index=True,
                default=apps.profiles.models.get_next_artist_position,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="charactertag",
            name="display_position",
            field=models.FloatField(
                db_index=True,
                default=apps.profiles.models.get_next_character_position,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="display_position",
            field=models.FloatField(
                db_index=True,
                default=apps.profiles.models.get_next_submission_position,
                unique=True,
            ),
        ),
    ]
