# Generated by Django 4.2.11 on 2024-04-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0142_unique_display_positions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mailchimp_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="offered_mailchimp",
        ),
    ]
