# Generated by Django 4.2.11 on 2024-05-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0143_remove_user_mailchimp_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="taggable",
        ),
    ]
