# Generated by Django 4.2.11 on 2024-05-20 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0144_remove_character_taggable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="created_on",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
