# Generated by Django 4.2.11 on 2024-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0145_alter_submission_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Enabling features all of a user's products and puts them in the featured users listing. This is mostly managed by a scheduled task, but it can be manually triggered here, too.",
            ),
        ),
    ]
