# Generated by Django 5.0.7 on 2024-08-13 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0146_user_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPowers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle_disputes", models.BooleanField(default=False)),
                ("view_social_data", models.BooleanField(default=False)),
                ("view_financials", models.BooleanField(default=False)),
                ("moderate_content", models.BooleanField(default=False)),
                ("moderate_discussion", models.BooleanField(default=False)),
                ("table_seller", models.BooleanField(default=False)),
                ("view_as", models.BooleanField(default=False)),
                ("administrate_users", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_powers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
