# Generated by Django 5.0.9 on 2024-09-18 14:26

import apps.profiles.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0045_case_insensitive_collation"),
        ("profiles", "0147_staffpowers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_collation="case_insensitive",
                db_index=True,
                max_length=40,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                    apps.profiles.models.banned_named_validator,
                    apps.profiles.models.banned_prefix_validator,
                ],
            ),
        ),
    ]
