# Generated by Django 5.1.1 on 2024-09-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0149_alter_user_email_nulled_sociallink_socialsettings"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
