---
- name: Install postfix
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - opendkim
    - opendkim-tools

- name: Configure Postfix
  template:
    src: "templates/main.cf"
    dest: "/etc/postfix/main.cf"
  notify:
    - restart postfix

- name: Ensure header checks configuration file
  file:
    path: /etc/postfix/header_checks
    state: touch
  changed_when: false

- name: Add dkim key
  copy:
    src: "keys/{{env_prefix}}/mail/mail.key"
    dest: /etc/mail/mail.key
    mode: 0600
    owner: opendkim
  notify:
    - restart opendkim

- name: Configure OpenDKIM
  template:
    src: "templates/opendkim.conf"
    dest: "/etc/opendkim.conf"
  notify:
    - restart opendkim
    - restart postfix


- name: Ensure OpenDKIM is running
  service:
    name: opendkim
    enabled: yes
    state: started

- name: Ensure Postfix is running
  service:
    name: postfix
    enabled: yes
    state: started
