# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 18:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("lib", "0001_initial"),
        ("lib", "0002_auto_20171020_1521"),
        ("lib", "0003_comment_edited"),
        ("lib", "0004_comment_deleted"),
        ("lib", "0005_auto_20171212_2302"),
        ("lib", "0006_auto_20171219_2223"),
        ("lib", "0007_auto_20180105_1850"),
        ("lib", "0008_event_recalled"),
        ("lib", "0009_auto_20180105_1855"),
        ("lib", "0010_auto_20180105_1858"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=8000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("edited_on", models.DateTimeField(auto_now=True)),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="lib.Comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("edited", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ("created_on",),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "New Submission"),
                            (1, "New Follower"),
                            (2, "Character Transfer Request"),
                            (3, "Character Tag Approval"),
                            (4, "New Comment"),
                            (5, "New Character"),
                            (7, "Commission Slots Available"),
                            (6, "New Product"),
                            (11, "New Auction"),
                            (8, "New Submission of Character"),
                            (9, "New Portfolio Item"),
                            (10, "Submission Tag Approval"),
                            (12, "Announcement"),
                            (13, "System-wide announcement"),
                        ],
                        db_index=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(db_index=True, default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lib.Event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "New Submission"),
                            (1, "New Follower"),
                            (2, "Character Transfer Request"),
                            (3, "Character Tag Approval"),
                            (4, "New Comment"),
                            (5, "New Character"),
                            (7, "Commission Slots Available"),
                            (6, "New Product"),
                            (11, "New Auction"),
                            (8, "New Submission of Character"),
                            (9, "New Portfolio Item"),
                            (14, "New Favorite"),
                            (10, "Submission Tag Approval"),
                            (12, "Announcement"),
                            (13, "System-wide announcement"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("implicit", models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "New Submission"),
                    (1, "New Follower"),
                    (2, "Character Transfer Request"),
                    (3, "Character Tag Approval"),
                    (4, "New Comment"),
                    (5, "New Character"),
                    (7, "Commission Slots Available"),
                    (6, "New Product"),
                    (11, "New Auction"),
                    (8, "New Submission of Character"),
                    (9, "New Portfolio Item"),
                    (14, "New Favorite"),
                    (10, "Submission Tag Approval"),
                    (12, "Announcement"),
                    (13, "System-wide announcement"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set([("type", "subscriber", "object_id", "content_type")]),
        ),
        migrations.AddField(
            model_name="event",
            name="recalled",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
