# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_squashed_0010_auto_20180105_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
