# Generated by Django 5.1.2 on 2024-11-04 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ("lib", "0020_auto_20190314_1134"),
        ("lib", "0021_asset"),
        ("lib", "0022_auto_20190516_2237"),
        ("lib", "0023_recursive_comments"),
        ("lib", "0024_auto_20190725_2023"),
        ("lib", "0025_populate_assets"),
        ("lib", "0026_auto_20191125_1734"),
        ("lib", "0027_auto_20191125_1734"),
        ("lib", "0028_genericreference"),
        ("lib", "0029_auto_20200324_1542"),
        ("lib", "0030_comment_extra_context"),
        ("lib", "0031_subscribe_waitlist"),
        ("lib", "0032_auto_20200722_1419"),
        ("lib", "0033_auto_20210422_1554"),
        ("lib", "0033_auto_20210721_1001"),
        ("lib", "0034_merge_0033_auto_20210422_1554_0033_auto_20210721_1001"),
        ("lib", "0035_remove_portrait_subscriptions"),
        ("lib", "0036_auto_20220106_1410"),
        ("lib", "0037_auto_20221030_1740"),
        ("lib", "0038_alter_tag_name"),
        ("lib", "0039_alter_event_type_alter_subscription_type"),
        ("lib", "0040_alter_event_type_alter_subscription_type"),
        ("lib", "0041_note"),
        ("lib", "0042_emailpreference"),
        ("lib", "0043_set_site_name"),
        ("lib", "0044_create_shopping_cart"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("lib", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="lib.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="top_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="emailpreference",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="emailpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="genericreference",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="modifiedmarker",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
