# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 19:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0002_subscription_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
