# Generated by Django 5.1.2 on 2024-11-04 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("lib", "0002_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    replaces = [
        ("lib", "0045_case_insensitive_collation"),
        ("lib", "0046_drop_citext"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifiedmarker",
            name="deliverable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.deliverable",
            ),
        ),
        migrations.AddField(
            model_name="modifiedmarker",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="sales.order"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="lib.event",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="readmarker",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="readmarker",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailpreference",
            unique_together={("user", "type", "content_type")},
        ),
        migrations.AlterUniqueTogether(
            name="genericreference",
            unique_together={("object_id", "content_type")},
        ),
        migrations.AlterUniqueTogether(
            name="modifiedmarker",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="readmarker",
            unique_together={("content_type", "object_id", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("type", "subscriber", "object_id", "content_type")},
        ),
    ]
