# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_comment_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
