# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0005_auto_20171212_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'New Submission'), (1, 'New Follower'), (2, 'Character Transfer Request'), (3, 'Character Tag Approval'), (4, 'New Comment'), (5, 'New Character'), (7, 'Commission Slots Available'), (6, 'New Product'), (11, 'New Auction'), (8, 'New Submission of Character'), (9, 'New Portfolio Item'), (10, 'Submission Tag Approval'), (12, 'Announcement'), (13, 'System-wide announcement')], db_index=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'New Submission'), (1, 'New Follower'), (2, 'Character Transfer Request'), (3, 'Character Tag Approval'), (4, 'New Comment'), (5, 'New Character'), (7, 'Commission Slots Available'), (6, 'New Product'), (11, 'New Auction'), (8, 'New Submission of Character'), (9, 'New Portfolio Item'), (10, 'Submission Tag Approval'), (12, 'Announcement'), (13, 'System-wide announcement')], db_index=True)),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
