# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0008_auto_20180118_1516"),
        ("profiles", "0010_auto_20180125_1502"),
    ]

    database_operations = []

    state_operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.SlugField(db_index=True, unique=True, primary_key=True),
                ),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
