# Generated by Django 2.0.4 on 2018-05-29 20:25

from apps.lib.models import (
    COMMISSIONS_OPEN,
    ORDER_UPDATE,
    REFUND,
    REVISION_UPLOADED,
    SALE_UPDATE,
)
from django.db import migrations

EMAILABLE = (COMMISSIONS_OPEN, ORDER_UPDATE, REVISION_UPLOADED, SALE_UPDATE, REFUND)


def set_email_field(apps, schema):
    Subscription = apps.get_model("lib", "Subscription")
    Subscription.objects.filter(type__in=EMAILABLE).update(email=True)


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0013_subscription_email"),
    ]

    operations = [migrations.RunPython(set_email_field, reverse_code=lambda x, y: None)]
