# Generated by Django 2.0.4 on 2018-05-29 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0013_subscription_email"),
    ]
    # Historical migration. Operation no longer needed.
    operations = []
