# Generated by Django 2.0.8 on 2018-09-21 18:41

from django.db import migrations
from easy_thumbnails.files import generate_all_aliases


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0018_auto_20180723_1528"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
