# Generated by Django 2.1.5 on 2019-05-16 22:13

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lib", "0020_auto_20190314_1134"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        upload_to="assets/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    "ACC",
                                    "AE",
                                    "AI",
                                    "AN",
                                    "AVI",
                                    "BMP",
                                    "DGN",
                                    "DOC",
                                    "DOCH",
                                    "DOCM",
                                    "DOCX",
                                    "DOTH",
                                    "DW",
                                    "DWFX",
                                    "DWG",
                                    "DXF",
                                    "EPS",
                                    "F4A",
                                    "F4V",
                                    "FLV",
                                    "FS",
                                    "GIF",
                                    "IND",
                                    "JPEG",
                                    "JPG",
                                    "JPP",
                                    "LR",
                                    "M4V",
                                    "MIDI",
                                    "MKV",
                                    "MOV",
                                    "MP3",
                                    "MP4",
                                    "MPEG",
                                    "MPG",
                                    "OGA",
                                    "OGG",
                                    "OGV",
                                    "PDF",
                                    "PNG",
                                    "PS",
                                    "PSD",
                                    "RTF",
                                    "SVG",
                                    "SWF",
                                    "TIF",
                                    "TIFF",
                                    "TXT",
                                    "VTX",
                                    "WAV",
                                    "WDP",
                                    "WEBM",
                                    "WMA",
                                    "WMV",
                                    "ZIP",
                                )
                            )
                        ],
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("edited_on", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
