# Generated by Django 2.1.5 on 2019-05-16 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("lib", "0021_asset")]

    # Historical migration. Operation no longer needed.
    operations = []
