# Generated by Django 2.2.1 on 2019-06-26 07:03
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.db.models import F


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0022_auto_20190516_2237"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
