# Generated by Django 2.2.1 on 2019-07-25 20:23

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0023_recursive_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='art/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ACC', 'AE', 'AI', 'AN', 'AVI', 'BMP', 'DGN', 'DOC', 'DOCH', 'DOCM', 'DOCX', 'DOTH', 'DW', 'DWFX', 'DWG', 'DXF', 'EPS', 'F4A', 'F4V', 'FLV', 'FS', 'GIF', 'IND', 'JPEG', 'JPG', 'JPP', 'LR', 'M4V', 'MIDI', 'MKV', 'MOV', 'MP3', 'MP4', 'MPEG', 'MPG', 'OGA', 'OGG', 'OGV', 'PDF', 'PNG', 'PS', 'PSD', 'RTF', 'SVG', 'SWF', 'TIF', 'TIFF', 'TXT', 'VTX', 'WAV', 'WDP', 'WEBM', 'WMA', 'WMV', 'ZIP'))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'New Character'), (1, 'New Watcher'), (3, 'Character Tagged'), (4, 'New Comment'), (7, 'Commission Slots Available'), (6, 'New Product'), (11, 'New Auction'), (18, 'Update'), (22, 'Revision Uploaded'), (19, 'Sale Update'), (15, 'Dispute Filed'), (16, 'Refund Processed'), (8, 'New Submission of Character'), (14, 'New Favorite'), (10, 'Submission Tagged'), (17, 'Submission tagged with Character'), (20, 'Tagged as the artist of a submission'), (21, 'Tagged the artist of a submission'), (12, 'Announcement'), (13, 'System-wide announcement'), (27, 'Renewal Failure'), (28, 'Subscription Deactivated'), (30, 'New Journal Posted'), (31, 'Token Issued'), (32, 'Bank Transfer Failed')], db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.IntegerField(choices=[(0, 'New Character'), (1, 'New Watcher'), (3, 'Character Tagged'), (4, 'New Comment'), (7, 'Commission Slots Available'), (6, 'New Product'), (11, 'New Auction'), (18, 'Update'), (22, 'Revision Uploaded'), (19, 'Sale Update'), (15, 'Dispute Filed'), (16, 'Refund Processed'), (8, 'New Submission of Character'), (14, 'New Favorite'), (10, 'Submission Tagged'), (17, 'Submission tagged with Character'), (20, 'Tagged as the artist of a submission'), (21, 'Tagged the artist of a submission'), (12, 'Announcement'), (13, 'System-wide announcement'), (27, 'Renewal Failure'), (28, 'Subscription Deactivated'), (30, 'New Journal Posted'), (31, 'Token Issued'), (32, 'Bank Transfer Failed')], db_index=True),
        ),
    ]
