# Generated by Django 2.2.1 on 2019-07-25 20:25

from django.db import migrations
from django.db.models import Exists, OuterRef
from easy_thumbnails.alias import aliases
from easy_thumbnails.engine import NoSourceGenerator
from easy_thumbnails.exceptions import InvalidImageFormatError
from easy_thumbnails.files import generate_all_aliases, get_thumbnailer


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0024_auto_20190725_2023"),
        ("profiles", "0089_auto_20190725_2023"),
        ("sales", "0050_auto_20190725_2023"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
