# Generated by Django 2.2.1 on 2019-11-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0025_populate_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="thread_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="top_content_type",
            field=models.ForeignKey(
                blank=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="top_object_id",
            field=models.PositiveIntegerField(blank=False, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "New Character"),
                    (1, "New Watcher"),
                    (3, "Character Tagged"),
                    (4, "New Comment"),
                    (7, "Commission Slots Available"),
                    (6, "New Product"),
                    (11, "New Auction"),
                    (18, "Update"),
                    (22, "Revision Uploaded"),
                    (19, "Sale Update"),
                    (15, "Dispute Filed"),
                    (16, "Refund Processed"),
                    (8, "New Submission of Character"),
                    (14, "New Favorite"),
                    (10, "Submission Tagged"),
                    (17, "Submission tagged with Character"),
                    (20, "Tagged as the artist of a submission"),
                    (21, "Tagged the artist of a submission"),
                    (12, "Announcement"),
                    (13, "System-wide announcement"),
                    (27, "Renewal Failure"),
                    (28, "Subscription Deactivated"),
                    (30, "New Journal Posted"),
                    (32, "Bank Transfer Failed"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "New Character"),
                    (1, "New Watcher"),
                    (3, "Character Tagged"),
                    (4, "New Comment"),
                    (7, "Commission Slots Available"),
                    (6, "New Product"),
                    (11, "New Auction"),
                    (18, "Update"),
                    (22, "Revision Uploaded"),
                    (19, "Sale Update"),
                    (15, "Dispute Filed"),
                    (16, "Refund Processed"),
                    (8, "New Submission of Character"),
                    (14, "New Favorite"),
                    (10, "Submission Tagged"),
                    (17, "Submission tagged with Character"),
                    (20, "Tagged as the artist of a submission"),
                    (21, "Tagged the artist of a submission"),
                    (12, "Announcement"),
                    (13, "System-wide announcement"),
                    (27, "Renewal Failure"),
                    (28, "Subscription Deactivated"),
                    (30, "New Journal Posted"),
                    (32, "Bank Transfer Failed"),
                ],
                db_index=True,
            ),
        ),
    ]
