# Generated by Django 2.2.1 on 2019-11-25 17:34
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0026_auto_20191125_1734"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
