# Generated by Django 3.0.4 on 2020-03-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0027_auto_20191125_1734"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericReference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
    ]
