# Generated by Django 3.0.6 on 2020-06-17 13:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0029_auto_20200324_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="extra_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
    ]
