# Generated by Django 3.0.6 on 2020-07-02 17:30
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0030_comment_extra_context"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
