# Generated by Django 3.1.13 on 2021-07-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0032_auto_20200722_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hash',
            field=models.BinaryField(db_index=True, default=b'', max_length=32),
        ),
        migrations.AlterField(
            model_name='comment',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
