# Generated by Django 3.2.6 on 2021-08-20 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0033_auto_20210422_1554"),
        ("lib", "0033_auto_20210721_1001"),
    ]

    operations = []
