# Generated by Django 3.2.9 on 2021-11-30 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0034_merge_0033_auto_20210422_1554_0033_auto_20210721_1001"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
