# Generated by Django 3.2.15 on 2022-10-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0036_auto_20220106_1410'),
    ]

    operations = [
        # Need this to convert over to our new fork of Django-hitcount
        migrations.RunSQL(
            """
            ALTER TABLE hitcount_hit_count ALTER COLUMN object_pk SET DATA TYPE integer USING object_pk::integer;
            """
        )
    ]
