# Generated by Django 4.2.10 on 2024-02-29 17:16

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0042_emailpreference"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
