# Generated by Django 5.0.9 on 2024-09-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0045_case_insensitive_collation"),
        ("profiles", "0148_alter_user_username"),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP EXTENSION IF EXISTS "citext"',
            reverse_sql='CREATE EXTENSION IF NOT EXISTS "citext"',
        )
    ]
