export interface TerseUser {
  id: number,
  username: string,
  avatar_url: string,
  biography: string,
  has_products: boolean,
  faborites_hidden: boolean,
  watching: boolean,
  blocked: boolean,
  commission_info: string,
  stars: string|null,
  escrow_disabled: boolean,
  is_staff: boolean,
  is_superuser: boolean,
  artist_mode: boolean|null,
  taggable: boolean,
  hits: number,
  watches: number,
  guest: boolean,
}
