export interface TerseUser {
  id: number,
  username: string,
  avatar_url: string,
  biography: string,
  has_products: boolean,
  favorites_hidden: boolean,
  watching: boolean,
  blocked: boolean,
  stars: string|null,
  is_staff: boolean,
  is_superuser: boolean,
  artist_mode: boolean|null,
  taggable: boolean,
  hits: number,
  watches: number,
  guest: boolean,
  // Not actually here, but avoids issues with compatibility elsewhere.
  sfw_mode: boolean,
  verified_email: boolean,
}
