---
- name: restart uwsgi
  service: name=uwsgi state=restarted

- name: collect static assets
  become: yes
  become_user: "{{ env_prefix }}"
  shell: "source ~/.profile && source ~/bin/activate && cd ~/artconomy && ./manage.py collectstatic -v0 --noinput && npm run build && echo '{{ static_status.digest }}' > {{ home }}/.static_hash"
  args:
    executable: "/bin/bash"
  register: result

- name: migrator
  become: yes
  become_user: "{{ env_prefix }}"
  shell: "source ~/.profile && source ~/bin/activate && cd ~/artconomy && yes no | ./manage.py migrate && echo '{{ migrations_status.digest }}' > ~/.migrations_hash"
  args:
    executable: "/bin/bash"
