---
- name: Artconomy Stage Deployment
  become: true
  become_user: root
  hosts: stage

  roles:
    - sysconfig
    - postfix
    - firewall
    - postgres
    - letsencrypt
    - nginx
    - app
    - prerender
    # - blog
    - rabbitmq
    - celery