# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 18:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_parallel',
            field=models.IntegerField(blank=True, default=None, help_text='How many of these you are willing to have in your backlog at one time.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
