# Generated by Django 5.1.4 on 2025-01-04 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_add_compare_at_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="removed_on",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="removed_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Improperly tagged"),
                    (1, "Improperly rated"),
                    (2, "Spammy Content"),
                    (3, "Copyright Claimed"),
                    (4, "Explicit Photographs"),
                    (5, "Illegal Content"),
                ],
                db_index=True,
                null=True,
            ),
        ),
    ]
