# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_auto_20180116_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="lib.Tag"
            ),
        ),
    ]
