# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170922_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upfront_percentage',
        ),
    ]
