# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtoken',
            name='cvv_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='creditcardtoken',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
