# Generated by Django 5.1.7 on 2025-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_lineitem_category_alter_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='connection_fee_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='category',
            field=models.IntegerField(choices=[(420, 'Payment'), (400, 'Artconomy Service Fee'), (418, 'Processing fee (non-shield)'), (401, 'Escrow hold'), (402, 'Escrow release'), (403, 'Escrow refund'), (404, 'Subscription dues'), (405, 'Refund for subscription dues'), (406, 'Cash withdrawal'), (408, 'Third party fee'), (409, 'Premium service bonus'), (410, 'Internal Transfer'), (411, 'Third party refund'), (415, 'Extra item'), (412, 'Correction'), (413, 'Table Service'), (414, 'Taxes'), (416, 'Vendor Payment'), (417, 'Payout Reversal'), (419, 'Tip')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='category',
            field=models.IntegerField(choices=[(420, 'Payment'), (400, 'Artconomy Service Fee'), (418, 'Processing fee (non-shield)'), (401, 'Escrow hold'), (402, 'Escrow release'), (403, 'Escrow refund'), (404, 'Subscription dues'), (405, 'Refund for subscription dues'), (406, 'Cash withdrawal'), (408, 'Third party fee'), (409, 'Premium service bonus'), (410, 'Internal Transfer'), (411, 'Third party refund'), (415, 'Extra item'), (412, 'Correction'), (413, 'Table Service'), (414, 'Taxes'), (416, 'Vendor Payment'), (417, 'Payout Reversal'), (419, 'Tip')], db_index=True),
        ),
    ]
