# Generated by Django 5.2.4 on 2025-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_lineitem_category_alter_invoice_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="auto_redact_on",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="redact_available_on",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="redacted_on",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
