# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20171006_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Payment Pending'), (3, 'Queued'), (4, 'In Progress'), (5, 'Review'), (6, 'Cancelled'), (7, 'Disputed'), (8, 'Completed')], db_index=True, default=1),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
