# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_auto_20171019_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.IntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'American Express'), (4, 'Discover'), (5, 'Diners Club')], default=1)),
                ('last_four', models.CharField(max_length=4)),
                ('payment_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
