# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_creditcardtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proposed_adjustment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='proposed_adjustment_currency',
        ),
    ]
