# Generated by Django 2.0.2 on 2018-03-05 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arbitrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
