# Generated by Django 5.2.4 on 2025-07-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_serviceplan_connection_fee_waived_and_more"),
    ]

    operations = [
        # These have all been manually filled in production.
        migrations.AlterField(
            model_name="lineitem",
            name="category",
            field=models.IntegerField(
                choices=[
                    (420, "Payment"),
                    (400, "Artconomy Service Fee"),
                    (418, "Processing fee (non-shield)"),
                    (401, "Escrow hold"),
                    (402, "Escrow release"),
                    (403, "Escrow refund"),
                    (404, "Subscription dues"),
                    (405, "Refund for subscription dues"),
                    (406, "Cash withdrawal"),
                    (408, "Third party fee"),
                    (409, "Premium service bonus"),
                    (410, "Internal Transfer"),
                    (411, "Third party refund"),
                    (415, "Extra item"),
                    (412, "Correction"),
                    (413, "Table Service"),
                    (414, "Taxes"),
                    (416, "Vendor Payment"),
                    (417, "Payout Reversal"),
                    (419, "Tip"),
                    (421, "Top-up"),
                ],
                db_index=True,
            ),
        ),
    ]
