# Generated by Django 5.2.4 on 2025-08-06 14:23

from django.db import migrations, models
from django.db.models import F


def set_cascade_from(apps, schema):
    LineItem = apps.get_model("sales", "LineItem")
    LineItem.objects.all().update(cascade_under=F("priority"))


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_alter_lineitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="cascade_under",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.RunPython(
            set_cascade_from,
            reverse_code=lambda x, y: None,
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="cascade_under",
            field=models.IntegerField(db_index=True),
        ),
    ]
