# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0009_auto_20171111_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='escrow_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_hold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.IntegerField(choices=[(200, 'Sale of good or service'), (201, 'Disbursement to account'), (202, 'Refund')], db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='source',
            field=models.IntegerField(choices=[(100, 'Credit Card'), (101, 'Bank Transfer')], db_index=True),
        ),
    ]
