# Generated by Django 2.0.3 on 2018-03-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0009_auto_20180312_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
