# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_revision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('created_on',)},
        ),
    ]
