# Generated by Django 2.0.3 on 2018-04-02 18:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20180327_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adjustment_expected_turnaround',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='adjustment_task_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_turnaround',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='task_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='expected_turnaround',
            field=models.DecimalField(decimal_places=2, help_text='Number of days completion is expected to take.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
