# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 19:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20171212_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, 'Sketch'), (1, 'Full Body'), (2, 'Reference Sheet'), (3, 'Convention badge/button/card'), (4, 'Single Icon'), (5, 'Icon/Sticker set'), (6, 'Headshot'), (7, 'Chibi'), (8, 'Game asset/skin'), (9, '3D Rendered Image'), (10, 'Animated (2D)'), (11, 'Animated (3D)'), (12, 'Short Story'), (13, 'Long story'), (14, 'Music'), (15, 'Other')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_parallel',
            field=models.IntegerField(blank=True, default=0, help_text='How many of these you are willing to have in your backlog at one time.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Clean/Safe for work'), (1, 'Risque/mature, not adult content but not safe for work'), (2, 'Adult content, not safe for work'), (3, 'Offensive/Disturbing to most viewers, not safe for work')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='revision',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Clean/Safe for work'), (1, 'Risque/mature, not adult content but not safe for work'), (2, 'Adult content, not safe for work'), (3, 'Offensive/Disturbing to most viewers, not safe for work')], db_index=True, default=0),
        ),
    ]
