# Generated by Django 2.0.3 on 2018-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20180402_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parallel',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
