# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 21:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20171227_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adjustment',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=4),
        ),
    ]
