# Generated by Django 2.0.3 on 2018-04-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_product_parallel'),
    ]

    operations = [
        migrations.RenameField('Revision', 'uploaded_by', 'owner'),
        migrations.RenameField('Product', 'uploaded_by', 'owner'),
    ]
