# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 17:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_order_stream_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='revisions_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='revisions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
