# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20180102_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='source',
            field=models.IntegerField(choices=[(100, 'Credit Card'), (101, 'Bank Transfer'), (102, 'Escrow Holdings'), (203, 'Cash Holdings')], db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='txn_id',
            field=models.CharField(max_length=40),
        ),
    ]
