# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20180103_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='placed_on',
            new_name='created_on',
        ),
    ]
