# Generated by Django 2.0.4 on 2018-05-03 20:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0018_auto_20180424_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Payment Pending'), (3, 'Queued'), (4, 'In Progress'), (5, 'Review'), (6, 'Cancelled'), (7, 'Disputed'), (8, 'Completed'), (9, 'Refunded')], db_index=True, default=4)),
                ('task_weight', models.IntegerField(default=0)),
                ('expected_turnaround', models.DecimalField(decimal_places=2, help_text='Number of days completion is expected to take.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.CharField(max_length=5000)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_turnaround',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of days completion is expected to take.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
