# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20180103_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
