# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disputed_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
