# Generated by Django 2.0.4 on 2018-06-06 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
