# Generated by Django 2.0.6 on 2018-06-19 21:30

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_rating_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=6),
        ),
    ]
