# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20180108_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrecord',
            old_name='payment_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='escrow_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debits', to=settings.AUTH_USER_MODEL),
        ),
    ]
