# Generated by Django 2.0.7 on 2018-07-19 15:02

import apps.sales.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_order_started_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(default=apps.sales.models.mini_key, max_length=8)),
                ('expires_on', models.DateTimeField(db_index=True, default=apps.sales.models.tomorrow)),
                ('email', models.EmailField(max_length=254)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Product')),
            ],
        ),
    ]
