# Generated by Django 2.0.7 on 2018-07-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_ordertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='placeholder',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='auction',
        ),
        migrations.AlterField(
            model_name='ordertoken',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='sales.Product'),
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Placeholder',
        ),
    ]
