# Generated by Django 2.0.7 on 2018-08-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0029_auto_20180719_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="finalize_on",
            field=models.DateField(db_index=True, default=None, null=True),
        ),
    ]
