# Generated by Django 2.0.7 on 2018-08-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0030_paymentrecord_finalize_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="escrow_disabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
