# Generated by Django 2.0.8 on 2018-09-12 18:18

from decimal import Decimal

import apps.sales.models
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0054_user_escrow_disabled"),
        ("sales", "0031_auto_20180821_1929"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactertransfer",
            name="completed_on",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="charactertransfer",
            name="included_assets",
            field=models.ManyToManyField(
                related_name="character_transfers", to="profiles.ImageAsset"
            ),
        ),
        migrations.AlterField(
            model_name="charactertransfer",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="characters",
            field=models.ManyToManyField(blank=True, to="profiles.Character"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=djmoney.models.fields.MoneyField(
                db_index=True,
                decimal_places=2,
                default=Decimal("0.0"),
                default_currency="USD",
                max_digits=6,
            ),
        ),
    ]
