# Generated by Django 2.0.8 on 2018-09-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_auto_20180912_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
