# Generated by Django 2.0.8 on 2018-09-21 16:21

from django.db import migrations

from apps.sales.models import update_artist_load


def update_availability(apps, schema):
    User = apps.get_model('profiles', 'User')
    for user in User.objects.filter(products__isnull=False):
        update_artist_load(user, user.products.first())


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_product_available'),
    ]

    operations = [
        migrations.RunPython(update_availability, lambda x, y: None)
    ]
