# Generated by Django 2.0.7 on 2018-09-25 22:50

from decimal import Decimal
import django.core.validators
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adjustment',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.10'))]),
        ),
    ]
