# Generated by Django 2.0.8 on 2018-11-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0036_auto_20180925_2250"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
