# Generated by Django 2.1.5 on 2019-02-01 14:52
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0037_product_featured"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
