# Generated by Django 2.1.5 on 2019-02-01 14:52
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


COMMENT = 4


def ensure_seller_emails(apps, schema):
    Subscription = apps.get_model('lib', 'Subscription')
    Order = apps.get_model('sales', 'Order')
    Subscription.objects.filter(
        content_type_id=ContentType.objects.get_for_model(Order).id, type=COMMENT
    ).update(email=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_product_featured'),
    ]

    operations = [
        migrations.RunPython(ensure_seller_emails, reverse_code=lambda x, y: None)
    ]
