# Generated by Django 2.1.5 on 2019-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0039_auto_20190310_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
