# Generated by Django 2.1.5 on 2019-04-04 02:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_auto_20190314_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='final_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='revisions_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
