# Generated by Django 2.1.5 on 2019-04-04 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0041_auto_20190404_0237"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
