# Generated by Django 2.1.5 on 2019-04-04 01:48

from django.db import migrations

NEW = 1
PAYMENT_PENDING = 2
REVIEW = 5
COMPLETED = 8


def set_final_uploaded(apps, schema):
    Order = apps.get_model("sales", "Order")
    Order.objects.filter(status__in=[REVIEW, COMPLETED]).update(final_uploaded=True)
    Order.objects.exclude(status__in=[NEW, PAYMENT_PENDING]).update(
        revisions_hidden=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0041_auto_20190404_0237"),
    ]

    operations = [
        migrations.RunPython(set_final_uploaded, reverse_code=lambda x, y: None)
    ]
