# Generated by Django 2.1.5 on 2019-07-01 13:31

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0042_auto_20190404_0237"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactertransfer",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="charactertransfer",
            name="character",
        ),
        migrations.RemoveField(
            model_name="charactertransfer",
            name="included_assets",
        ),
        migrations.RemoveField(
            model_name="charactertransfer",
            name="seller",
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=None,
                default_currency="USD",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=djmoney.models.fields.MoneyField(
                db_index=True,
                decimal_places=2,
                default=Decimal("0.0"),
                default_currency="USD",
                max_digits=6,
            ),
        ),
        migrations.DeleteModel(
            name="CharacterTransfer",
        ),
    ]
