# Generated by Django 2.1.5 on 2019-05-16 18:48

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_auto_20190404_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=6),
        ),
    ]
