# Generated by Django 2.1.5 on 2019-10-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0043_auto_20190701_1331"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placeholdersale",
            name="seller",
        ),
        migrations.DeleteModel(
            name="PlaceholderSale",
        ),
    ]
