# Generated by Django 2.1.5 on 2019-05-16 22:01

from django.db import migrations


# Empty migration obviated by upstream change.
class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_auto_20190516_1848'),
        ('profiles', '0073_auto_20190516_1847'),
    ]

    operations = [
    ]
