# Generated by Django 2.2.1 on 2019-06-10 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0046_auto_20190605_1418"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creditcardtoken",
            old_name="card_type",
            new_name="type",
        ),
    ]
