# Generated by Django 2.2.1 on 2019-06-10 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0047_auto_20190610_1449"),
        ("profiles", "0076_user_authorize_token"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
