# Generated by Django 2.2.1 on 2019-10-10 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0051_auto_20190725_2206"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
