# Generated by Django 2.2.1 on 2019-10-10 19:49

from django.db import migrations


ORDER_TOKEN_ISSUED = 31

def clear_token_events(apps, schema):
    Event = apps.get_model('lib', 'Event')
    Event.objects.filter(type=ORDER_TOKEN_ISSUED).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_auto_20190725_2206'),
    ]

    operations = [
        migrations.RunPython(clear_token_events, lambda x, y: None)
    ]
