# Generated by Django 2.2.1 on 2019-10-10 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_auto_20191010_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='type',
            field=models.IntegerField(choices=[(200, 'Sale of good or service'), (205, 'Internal Transfer'), (201, 'Initiated Disbursement'), (202, 'Disbursement completed'), (204, 'Refund')], db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_old',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='art/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ACC', 'AE', 'AI', 'AN', 'AVI', 'BMP', 'DGN', 'DOC', 'DOCH', 'DOCM', 'DOCX', 'DOTH', 'DW', 'DWFX', 'DWG', 'DXF', 'EPS', 'F4A', 'F4V', 'FLV', 'FS', 'GIF', 'IND', 'JPEG', 'JPG', 'JPP', 'LR', 'M4V', 'MIDI', 'MKV', 'MOV', 'MP3', 'MP4', 'MPEG', 'MPG', 'OGA', 'OGG', 'OGV', 'PDF', 'PNG', 'PS', 'PSD', 'RTF', 'SVG', 'SWF', 'TIF', 'TIFF', 'TXT', 'VTX', 'WAV', 'WDP', 'WEBM', 'WMA', 'WMV', 'ZIP'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_sales_product', to='lib.Asset'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='file_old',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='art/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('ACC', 'AE', 'AI', 'AN', 'AVI', 'BMP', 'DGN', 'DOC', 'DOCH', 'DOCM', 'DOCX', 'DOTH', 'DW', 'DWFX', 'DWG', 'DXF', 'EPS', 'F4A', 'F4V', 'FLV', 'FS', 'GIF', 'IND', 'JPEG', 'JPG', 'JPP', 'LR', 'M4V', 'MIDI', 'MKV', 'MOV', 'MP3', 'MP4', 'MPEG', 'MPG', 'OGA', 'OGG', 'OGV', 'PDF', 'PNG', 'PS', 'PSD', 'RTF', 'SVG', 'SWF', 'TIF', 'TIFF', 'TXT', 'VTX', 'WAV', 'WDP', 'WEBM', 'WMA', 'WMV', 'ZIP'))]),
        ),
        migrations.AlterField(
            model_name='revision',
            name='preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_sales_revision', to='lib.Asset'),
        ),
        migrations.DeleteModel(
            name='OrderToken',
        ),
    ]
