# Generated by Django 2.2.1 on 2019-10-15 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0053_auto_20191010_1455"),
        ("sales", "0044_auto_20191015_1554"),
    ]

    operations = []
