# Generated by Django 2.2.1 on 2019-10-17 19:04
from decimal import Decimal

from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.db.models import Sum
from django.utils import timezone
from moneyed import Money


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0055_auto_20191016_1348"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
