# Generated by Django 2.2.1 on 2019-10-23 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0056_convert_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="primary_submission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_sample_for",
                to="profiles.Submission",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="samples",
            field=models.ManyToManyField(
                related_name="is_sample_for", to="profiles.Submission"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="destination",
            field=models.IntegerField(
                choices=[
                    (300, "Credit Card"),
                    (301, "Bank Account"),
                    (302, "Escrow"),
                    (303, "Finalized Earnings, available for withdraw"),
                    (304, "Contingency reserve"),
                    (305, "Unannotated earnings"),
                    (306, "Card transaction fees"),
                    (307, "Other card fees"),
                    (307, "ACH Transaction fees"),
                    (308, "Other ACH fees"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="finalized_on",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="remote_id",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="response_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="source",
            field=models.IntegerField(
                choices=[
                    (300, "Credit Card"),
                    (301, "Bank Account"),
                    (302, "Escrow"),
                    (303, "Finalized Earnings, available for withdraw"),
                    (304, "Contingency reserve"),
                    (305, "Unannotated earnings"),
                    (306, "Card transaction fees"),
                    (307, "Other card fees"),
                    (307, "ACH Transaction fees"),
                    (308, "Other ACH fees"),
                ],
                db_index=True,
            ),
        ),
    ]
