# Generated by Django 2.2.1 on 2019-10-23 21:06
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from easy_thumbnails.alias import aliases
from easy_thumbnails.exceptions import InvalidImageFormatError
from easy_thumbnails.files import get_thumbnailer


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0057_auto_20191023_1605"),
        ("lib", "0025_populate_assets"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
