# Generated by Django 2.2.1 on 2019-10-31 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0059_auto_20191031_0805"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
