# Generated by Django 2.2.1 on 2019-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0061_auto_20191121_0855"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="adjustment_revisions",
            field=models.IntegerField(default=0),
        ),
    ]
