# Generated by Django 2.2.1 on 2019-12-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_order_adjustment_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trust_finalized',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
