# Generated by Django 2.2.1 on 2020-01-05 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0063_order_trust_finalized"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
