# Generated by Django 2.2.1 on 2020-01-05 12:13

from django.db import migrations
from django.db.models import F


def set_customer_email(apps, schema):
    Order = apps.get_model('sales', 'Order')
    for order in Order.objects.filter(buyer__guest=True):
        order.customer_email = order.buyer.guest_email
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0063_order_trust_finalized'),
    ]

    operations = [
        migrations.RunPython(set_customer_email, reverse_code=lambda x, y: None)
    ]
