# Generated by Django 2.2.1 on 2020-01-11 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_auto_20200105_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edited_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
