# Generated by Django 2.2.1 on 2020-01-11 14:11

from django.db import migrations


def set_initial_edit(apps, schema):
    Product = apps.get_model('sales', 'Product')
    for product in Product.objects.all():
        Product.objects.filter(id=product.id).update(edited_on=product.created_on)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0065_auto_20200111_0745'),
    ]

    operations = [
        migrations.RunPython(
            set_initial_edit,
            reverse_code=lambda x, y: None,
        )
    ]
