# Generated by Django 2.2.1 on 2020-01-11 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0065_auto_20200111_0745"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
