# Generated by Django 2.2.9 on 2020-01-23 15:29
from collections import defaultdict
from decimal import Decimal
from functools import reduce
from typing import TYPE_CHECKING, Dict, Iterator, List, Union

from apps.profiles.models import User
from apps.sales.models import TransactionRecord
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.db.models import F, Sum
from moneyed import Money


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0070_auto_20200123_1528"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
