# Generated by Django 2.2.9 on 2020-01-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0071_populate_line_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adjustment',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_currency',
            new_name='base_price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adjustment_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tip_currency',
        ),
    ]
