# Generated by Django 2.2.10 on 2020-02-12 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0072_auto_20200123_1537"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
