# Generated by Django 2.2.10 on 2020-02-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0075_remove_product_tax_rate'),
    ]

    operations = [
    ]
