# Generated by Django 2.2.10 on 2020-02-20 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0078_auto_20200220_0218"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
