# Generated by Django 2.2.10 on 2020-02-20 14:49

from django.db import migrations


def set_starting_price(apps, schema):
    Product = apps.get_model("sales", "Product")
    for product in Product.objects.all():
        product.starting_price = product.base_price
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0078_auto_20200220_0218"),
    ]

    operations = [
        migrations.RunPython(set_starting_price, reverse_code=lambda x, y: None)
    ]
