# Generated by Django 3.0.4 on 2020-03-24 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0081_auto_20200324_1100"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionrecord",
            name="targets",
            field=models.ManyToManyField(
                related_name="referencing_transactions", to="lib.GenericReference"
            ),
        ),
    ]
