# Generated by Django 3.0.4 on 2020-03-24 17:31
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0082_auto_20200324_1230"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
