# Generated by Django 3.0.4 on 2020-03-24 17:43

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0097_auto_20200317_1659"),
        ("sales", "0083_auto_20200324_1231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionrecord",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="transactionrecord",
            name="object_id",
        ),
    ]
