# Generated by Django 3.0.4 on 2020-03-26 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0084_auto_20200324_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payout_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
