# Generated by Django 3.0.4 on 2020-03-28 12:05
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0085_auto_20200326_1050"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
