# Generated by Django 3.0.5 on 2020-04-17 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import short_stuff.django.models
import short_stuff.lib


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0097_auto_20200317_1659'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0086_auto_20200328_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='auth_code',
            field=models.CharField(db_index=True, default='', max_length=6),
        ),
    ]
