# Generated by Django 3.0.4 on 2020-03-15 01:15
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0088_auto_20200314_1937"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
