# Generated by Django 3.0.6 on 2020-05-15 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0091_auto_20200515_1649"),
    ]

    operations = []
