# Generated by Django 3.0.6 on 2020-05-15 21:50

from django.db import migrations


def default_deliverable_names(apps, schema):
    Deliverable = apps.get_model("sales", "Deliverable")
    Deliverable.objects.filter(name="").update(name="Main")


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0091_auto_20200515_1649"),
    ]

    operations = [
        migrations.RunPython(default_deliverable_names, reverse_code=lambda x, y: None)
    ]
