# Generated by Django 3.0.6 on 2020-05-22 19:32
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0092_default_deliverable_name"),
    ]

    operations = []
