# Generated by Django 3.0.6 on 2020-05-29 15:02

import apps.lib.abstract_models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0029_auto_20200324_1542"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0093_auto_20200522_1432"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "Clean/Safe for work"),
                            (
                                1,
                                "Risque/mature, not adult content but not safe for "
                                "work",
                            ),
                            (2, "Adult content, not safe for work"),
                            (
                                3,
                                "Offensive/Disturbing to most viewers, not safe for "
                                "work",
                            ),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "file_old",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        upload_to="art/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    "ACC",
                                    "AE",
                                    "AI",
                                    "AN",
                                    "AVI",
                                    "BMP",
                                    "DGN",
                                    "DOC",
                                    "DOCH",
                                    "DOCM",
                                    "DOCX",
                                    "DOTH",
                                    "DW",
                                    "DWFX",
                                    "DWG",
                                    "DXF",
                                    "EPS",
                                    "F4A",
                                    "F4V",
                                    "FLV",
                                    "FS",
                                    "GIF",
                                    "IND",
                                    "JPEG",
                                    "JPG",
                                    "JPP",
                                    "LR",
                                    "M4V",
                                    "MIDI",
                                    "MKV",
                                    "MOV",
                                    "MP3",
                                    "MP4",
                                    "MPEG",
                                    "MPG",
                                    "OGA",
                                    "OGG",
                                    "OGV",
                                    "PDF",
                                    "PNG",
                                    "PS",
                                    "PSD",
                                    "RTF",
                                    "SVG",
                                    "SWF",
                                    "TIF",
                                    "TIFF",
                                    "TXT",
                                    "VTX",
                                    "WAV",
                                    "WDP",
                                    "WEBM",
                                    "WMA",
                                    "WMV",
                                    "ZIP",
                                )
                            )
                        ],
                    ),
                ),
                (
                    "preview_old",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True, default="", null=True, upload_to="thumbs/%Y/%m/%d/"
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("deliverables", models.ManyToManyField(to="sales.Deliverable")),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="full_sales_reference",
                        to="lib.Asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_sales_reference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preview",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preview_sales_reference",
                        to="lib.Asset",
                    ),
                ),
            ],
            options={
                "ordering": ["created_on"],
            },
            bases=(apps.lib.abstract_models.AssetThumbnailMixin, models.Model),
        ),
    ]
