# Generated by Django 3.0.6 on 2020-06-16 20:35
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

REFERENCE_UPLOADED = 35


def subscribe_references(apps, schema):
    Subscription = apps.get_model("lib", "Subscription")
    Deliverable = apps.get_model("sales", "Deliverable")
    deliverable_type = ContentType.objects.get_for_model(Deliverable)
    for deliverable in Deliverable.objects.all():
        Subscription.objects.get_or_create(
            subscriber=deliverable.order.seller,
            type=REFERENCE_UPLOADED,
            email=True,
            object_id=deliverable.id,
            content_type_id=deliverable_type.id,
        )
        if deliverable.order.buyer:
            Subscription.objects.get_or_create(
                subscriber=deliverable.order.buyer,
                type=REFERENCE_UPLOADED,
                email=True,
                object_id=deliverable.id,
                content_type_id=deliverable_type.id,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0094_reference"),
    ]

    operations = [migrations.RunPython(subscribe_references)]
