# Generated by Django 3.0.6 on 2020-06-16 20:35
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0094_reference"),
    ]

    operations = []
