# Generated by Django 3.0.6 on 2020-07-04 16:06
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0096_auto_20200630_1619"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
