# Generated by Django 3.0.6 on 2020-07-14 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0098_auto_20200714_0735"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
