# Generated by Django 3.0.6 on 2020-07-14 12:36

from django.db import migrations


def set_initial_products(apps, schema):
    Deliverable = apps.get_model("sales", "Deliverable")
    for deliverable in Deliverable.objects.all():
        deliverable.product = deliverable.order.product
        deliverable.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0098_auto_20200714_0735"),
    ]

    operations = [
        migrations.RunPython(set_initial_products, reverse_code=lambda x, y: None)
    ]
