# Generated by Django 3.0.6 on 2020-07-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0099_set_initial_deliverable_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
