# Generated by Django 3.0.6 on 2020-07-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0100_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
