# Generated by Django 3.0.6 on 2020-07-24 22:04

from django.db import migrations
from django.utils import timezone

CANCELLED = 6


def set_cancel_date(apps, schema):
    Deliverable = apps.get_model('sales', 'Deliverable')
    Deliverable.objects.filter(status=CANCELLED, cancelled_on__isnull=True).update(cancelled_on=timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0101_deliverable_cancelled_on'),
    ]

    operations = [
        migrations.RunPython(set_cancel_date, reverse_code=lambda x, y: None)
    ]
