# Generated by Django 3.0.6 on 2020-07-24 22:04

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0101_deliverable_cancelled_on"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
