# Generated by Django 3.0.6 on 2020-12-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0103_repair_payouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
