# Generated by Django 3.1.7 on 2021-03-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0105_auto_20201230_1041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="details",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="product",
            name="catalog_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
