# Generated by Django 3.1.7 on 2021-03-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0106_auto_20210330_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='processor',
            field=models.CharField(choices=[('authorize', 'EVO Authorize.net'), ('stripe', 'Stripe')], db_index=True, default='stripe', max_length=24),
        ),
    ]
