# Generated by Django 3.1.7 on 2021-03-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0107_auto_20210330_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='current_intent',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
    ]
