# Generated by Django 3.1.7 on 2021-04-22 20:54

import django.utils.timezone
import short_stuff.django.models
from django.conf import settings
from django.db import migrations, models

SALE = 0
SUBSCRIPTION = 1

INVOICE_TYPES = (
    (SALE, "Sale"),
    (SUBSCRIPTION, "Subscription"),
)


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0033_auto_20210422_1554"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0112_auto_20210415_1506"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    short_stuff.django.models.ShortCodeField(
                        primary_key=True,
                        serialize=False,
                        db_index=True,
                        default=short_stuff.gen_shortcode,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Sale"), (1, "Subscription")], default=0
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Draft"), (1, "Open"), (2, "Paid"), (5, "Void")],
                        default=0,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("paid_on", models.DateTimeField(db_index=True, null=True)),
                (
                    "stripe_token",
                    models.CharField(db_index=True, default="", max_length=50),
                ),
                (
                    "bill_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="referencing_invoices",
                        to="lib.GenericReference",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="creditcardtoken",
            name="stripe_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="creditcardtoken",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Visa"),
                    (2, "Mastercard"),
                    (3, "American Express"),
                    (4, "Discover"),
                    (5, "Diners Club"),
                    (6, "UnionPay"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="deliverable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="sales.deliverable",
            ),
        ),
        migrations.DeleteModel(
            name="PaymentRecord",
        ),
        migrations.AddField(
            model_name="deliverable",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliverables",
                to="sales.invoice",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="sales.invoice",
            ),
        ),
    ]
