# Generated by Django 3.1.7 on 2021-04-22 20:54
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from short_stuff import unslugify


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0113_auto_20210422_1554"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
