# Generated by Django 3.1.8 on 2021-04-28 21:27
from apps.sales.line_item_funcs import get_totals
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.utils import timezone
from moneyed import Money


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0115_remove_lineitem_deliverable"),
    ]

    operations = []
