# Generated by Django 3.1.8 on 2021-05-04 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0116_prefactor_reserve_fees"),
        ("sales", "0106_auto_20210327_1410"),
    ]

    operations = []
