# Generated by Django 3.2.4 on 2021-06-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0118_create_stripe_bank_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookrecord',
            name='connect',
            field=models.BooleanField(default=False),
        ),
    ]
