# Generated by Django 3.2.7 on 2021-10-07 22:28

from django.db import migrations
from django.db.models import F


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0120_auto_20210906_1336"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
