# Generated by Django 3.2.9 on 2021-11-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0121_fix_stuck_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionrecord",
            name="remote_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="destination_account",
            field=models.IntegerField(
                choices=[
                    (300, "Credit Card"),
                    (301, "Bank Account"),
                    (302, "Escrow"),
                    (303, "Finalized Earnings, available for withdraw"),
                    (
                        500,
                        "(Local Currency) Finalized Earnings, available for withdraw",
                    ),
                    (501, "(Local Currency) Bank Account"),
                    (304, "Contingency reserve"),
                    (305, "Unannotated earnings"),
                    (306, "Card transaction fees"),
                    (307, "Other card fees"),
                    (407, "Cash deposit"),
                    (308, "ACH Transaction fees"),
                    (309, "Other ACH fees"),
                    (310, "Tax staging"),
                    (311, "Tax"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="destination",
            field=models.IntegerField(
                choices=[
                    (300, "Credit Card"),
                    (301, "Bank Account"),
                    (302, "Escrow"),
                    (303, "Finalized Earnings, available for withdraw"),
                    (
                        500,
                        "(Local Currency) Finalized Earnings, available for withdraw",
                    ),
                    (501, "(Local Currency) Bank Account"),
                    (304, "Contingency reserve"),
                    (305, "Unannotated earnings"),
                    (306, "Card transaction fees"),
                    (307, "Other card fees"),
                    (407, "Cash deposit"),
                    (308, "ACH Transaction fees"),
                    (309, "Other ACH fees"),
                    (310, "Tax staging"),
                    (311, "Tax"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="source",
            field=models.IntegerField(
                choices=[
                    (300, "Credit Card"),
                    (301, "Bank Account"),
                    (302, "Escrow"),
                    (303, "Finalized Earnings, available for withdraw"),
                    (
                        500,
                        "(Local Currency) Finalized Earnings, available for withdraw",
                    ),
                    (501, "(Local Currency) Bank Account"),
                    (304, "Contingency reserve"),
                    (305, "Unannotated earnings"),
                    (306, "Card transaction fees"),
                    (307, "Other card fees"),
                    (407, "Cash deposit"),
                    (308, "ACH Transaction fees"),
                    (309, "Other ACH fees"),
                    (310, "Tax staging"),
                    (311, "Tax"),
                ],
                db_index=True,
            ),
        ),
    ]
