# Generated by Django 3.2.9 on 2021-11-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0122_convert_remote_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='remote_id',
        ),
    ]
