# Generated by Django 3.2.9 on 2021-12-30 19:00

from django.db import migrations
from django.db.models import Max


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0124_product_max_rating"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
