# Generated by Django 3.2.9 on 2022-01-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0036_auto_20220106_1410'),
        ('sales', '0125_set_initial_product_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.lineitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.genericreference')),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='annotations',
            field=models.ManyToManyField(related_name='line_items', through='sales.LineItemAnnotation', to='lib.GenericReference'),
        ),
    ]
