# Generated by Django 3.2.9 on 2022-02-01 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0126_auto_20220106_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="current_intent",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="paid_on",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="stripe_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="destination_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
