# Generated by Django 3.2.9 on 2022-02-01 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0127_invoice_current_intents"),
    ]

    operations = []
