# Generated by Django 3.2.12 on 2022-03-12 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0129_service_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="bill_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices_billed_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="serviceplan",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
