# Generated by Django 3.2.12 on 2022-03-13 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0131_auto_20220312_1917"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
