# Generated by Django 3.2.12 on 2022-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0132_invoice_status_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='creates_own_transactions',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
