# Generated by Django 3.2.13 on 2022-05-07 16:47

from django.db import migrations

from apps.sales.models import get_next_order_position, get_next_sale_position, get_next_case_position


def set_positions(apps, schema):
    Order = apps.get_model('sales', 'Order')
    for order in Order.objects.all().order_by('created_on'):
        order.order_display_position = get_next_order_position()
        order.sale_display_position = get_next_sale_position()
        order.case_display_position = get_next_case_position()
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0134_auto_20220507_1147'),
    ]

    operations = [
        migrations.RunPython(set_positions, reverse_code=lambda x, y: None)
    ]
