# Generated by Django 3.2.13 on 2022-05-07 16:47

from apps.sales.models import (
    get_next_case_position,
    get_next_order_position,
    get_next_sale_position,
)
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0134_auto_20220507_1147"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
