# Generated by Django 3.2.13 on 2022-05-07 16:53

import apps.sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0135_populate_order_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='case_display_position',
            field=models.FloatField(db_index=True, default=apps.sales.models.get_next_case_position),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_display_position',
            field=models.FloatField(db_index=True, default=apps.sales.models.get_next_order_position),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_display_position',
            field=models.FloatField(db_index=True, default=apps.sales.models.get_next_sale_position),
        ),
    ]
