# Generated by Django 3.2.13 on 2022-07-06 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0136_auto_20220507_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceplan',
            name='shield_percentage_price_currency',
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='shield_percentage_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('8'), help_text='Percentage amount applied to shield orders.', max_digits=5),
        ),
    ]
