# Generated by Django 3.2.13 on 2022-07-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0137_auto_20220706_1423'),
        ('sales', '0137_stripelocation_stripereader'),
    ]

    operations = [
    ]
