# Generated by Django 3.2.13 on 2022-07-10 12:55

from django.db import migrations


def set_null(apps, schema):
    CreditCardToken = apps.get_model('sales', 'CreditCardToken')
    CreditCardToken.objects.filter(stripe_token='').update(stripe_token=None)

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0139_alter_creditcardtoken_stripe_token'),
    ]

    operations = [
        migrations.RunPython(set_null)
    ]
