# Generated by Django 3.2.13 on 2022-07-10 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0139_alter_creditcardtoken_stripe_token"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
