# Generated by Django 3.2.13 on 2022-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0141_auto_20220719_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hide_details',
            field=models.BooleanField(default=False),
        ),
    ]
