# Generated by Django 3.2.13 on 2022-07-30 12:53

from django.db import migrations


def auto_hide(apps, schema):
    Order = apps.get_model("sales", "Order")
    Order.objects.filter(private=True).update(hide_details=True)


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0142_order_hide_details"),
    ]

    operations = [migrations.RunPython(auto_hide, reverse_code=lambda x, y: None)]
