# Generated by Django 3.2.13 on 2022-07-30 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0142_order_hide_details"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
