# Generated by Django 3.2.16 on 2023-01-03 21:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0144_auto_20221104_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='expected_turnaround',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='Number of days completion is expected to take.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
