# Generated by Django 3.2.15 on 2022-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0144_auto_20220906_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='creates_own_transactions',
            new_name='manually_created',
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='category',
            field=models.IntegerField(choices=[(400, 'Artconomy Service Fee'), (401, 'Escrow hold'), (402, 'Escrow release'), (403, 'Escrow refund'), (404, 'Subscription dues'), (405, 'Refund for subscription dues'), (406, 'Cash withdrawal'), (408, 'Third party fee'), (409, 'Premium service bonus'), (410, 'Internal Transfer'), (411, 'Third party refund'), (415, 'Extra item'), (412, 'Correction'), (5, 'Table Service'), (414, 'Taxes'), (416, 'Manual Payout'), (417, 'Payout Reversal')], db_index=True),
        ),
    ]
