# Generated by Django 3.2.15 on 2022-11-01 14:56

import apps.sales.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0145_auto_20220911_1140"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="issued_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_issued_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deliverable",
            name="processor",
            field=models.CharField(
                choices=[("authorize", "EVO Authorize.net"), ("stripe", "Stripe")],
                db_index=True,
                default=apps.sales.models.get_default_processor,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="stripereader",
            name="virtual",
            field=models.BooleanField(default=False),
        ),
    ]
