# Generated by Django 3.2.15 on 2022-11-01 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0146_auto_20221101_0956"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
