# Generated by Django 3.2.15 on 2022-11-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0144_auto_20221104_0624'),
        ('sales', '0147_annotate_issued_by'),
    ]

    operations = [
    ]
