# Generated by Django 3.2.16 on 2022-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0148_merge_0144_auto_20221104_0624_0147_annotate_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='discord_role_id',
            field=models.CharField(db_index=True, default='', help_text='Discord role ID to add to users who have this service plan.', max_length=30),
        ),
    ]
