# Generated by Django 3.2.16 on 2023-01-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0145_alter_expected_turnaround'),
        ('sales', '0151_cascade_fees_flag'),
    ]

    operations = [
    ]
