# Generated by Django 4.1.5 on 2023-01-25 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0155_flip_escrow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverable",
            name="escrow_disabled",
        ),
    ]
