# Generated by Django 4.1.5 on 2023-01-24 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0038_alter_tag_name'),
        ('sales', '0155_swap_escrow_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='escrow_disabled',
        ),
    ]
