# Generated by Django 4.1.5 on 2023-02-02 00:31

from django.db import migrations


def set_initial_escrow(apps, schema):
    User = apps.get_model('profiles', 'User')
    Product = apps.get_model('sales', 'Product')
    for user in User.objects.all():
        if hasattr(user, 'artist_profile'):
            user.products.all().update(escrow_enabled=user.artist_profile.escrow_enabled)
    Product.objects.filter(table_product=True).update(escrow_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0157_product_escrow_settings'),
    ]

    operations = [
        migrations.RunPython(set_initial_escrow, reverse_code=lambda x, y: None)
    ]
