# Generated by Django 4.1.5 on 2023-02-02 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0157_product_escrow_settings"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
