# Generated by Django 4.1.7 on 2023-02-20 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0160_remove_serviceplan_auto_shield"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="finalized_on",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
