# Generated by Django 4.1.7 on 2023-02-20 19:24

from apps.lib.models import ref_for_instance
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0161_deliverable_finalized_on"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
