# Generated by Django 4.1.7 on 2023-02-21 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0162_set_finalized_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payout_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payout_available",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
