# Generated by Django 4.1.7 on 2023-02-21 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0163_invoice_payout_sent"),
    ]

    operations = []
