# Generated by Django 4.1.7 on 2023-02-23 01:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lib", "0038_alter_tag_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0164_migrate_paid_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverable",
            name="payout_sent",
        ),
    ]
