# Generated by Django 4.1.7 on 2023-02-27 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib', '0039_alter_event_type_alter_subscription_type'),
        ('sales', '0165_remove_deliverable_payout_sent_alter_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='term_billed',
            field=models.BooleanField(db_index=True, default=False, help_text='Marked true when this deliverable has been credited on a monthly invoice (or otherwise would have been if such credits do not apply)'),
        ),
    ]
