# Generated by Django 4.1.7 on 2023-03-02 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0167_deliverable_auto_cancel_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceplan",
            name="waitlisting",
            field=models.BooleanField(
                default=False,
                db_index=True,
                help_text="Whether the seller can add waitlist products or else "
                "waitlist a particular order.",
            ),
        ),
    ]
