# Generated by Django 4.1.7 on 2023-03-26 13:08

from django.db import migrations

REVISION_APPROVED = 39


def populate_revision_subscriptions(apps, schema_editor):
    Revision = apps.get_model("sales", "Revision")
    Subscription = apps.get_model("lib", "Subscription")
    from django.contrib.contenttypes.models import ContentType

    content_type_id = ContentType.objects.get_for_model(Revision).id
    for revision in Revision.objects.all():
        Subscription.objects.get_or_create(
            type=REVISION_APPROVED,
            content_type_id=content_type_id,
            object_id=revision.id,
            subscriber=revision.owner,
            email=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0168_serviceplan_waitlisting"),
    ]

    operations = [
        migrations.RunPython(
            populate_revision_subscriptions, reverse_code=lambda x, y: None
        ),
    ]
