# Generated by Django 4.1.7 on 2023-03-26 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0168_serviceplan_waitlisting"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
