# Generated by Django 4.1.7 on 2023-04-10 19:57

import apps.sales.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0170_alter_transactionrecord_options_revision_approved_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="display_position",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
