# Generated by Django 4.1.7 on 2023-04-10 20:02

import apps.sales.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0171_product_display_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="display_position",
            field=models.FloatField(
                db_index=True, default=apps.sales.models.get_next_product_position
            ),
        ),
    ]
