# Generated by Django 4.2 on 2023-04-15 19:41
from hashlib import sha256

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0174_deliverable_commission_info_note"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
