# Generated by Django 4.2 on 2023-04-15 19:41
from hashlib import sha256

from django.db import migrations


def create_notes(apps, schema_editor):
    def note_for_text(text):
        return Note.objects.get_or_create(
            hash=sha256(text.encode("utf-8")).digest(), defaults={"text": text}
        )[0]

    Note = apps.get_model("lib", "Note")
    Deliverable = apps.get_model("sales", "Deliverable")
    for deliverable in Deliverable.objects.all():
        deliverable.commission_info_note = note_for_text(deliverable.commission_info)
        deliverable.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0174_deliverable_commission_info_note"),
    ]

    operations = [
        migrations.RunPython(create_notes, reverse_code=migrations.RunPython.noop),
    ]
