# Generated by Django 4.2 on 2023-04-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0175_create_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='commission_info',
        ),
        migrations.RenameField(
            model_name='deliverable',
            old_name='commission_info_note',
            new_name='commission_info',
        ),
    ]
