# Generated by Django 4.2 on 2023-05-06 19:09
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0177_deliverable_refunded_on_and_more"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
