# Generated by Django 4.2.3 on 2023-07-07 18:59
from decimal import Decimal

import djmoney
import short_stuff
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0178_set_refunded_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaypalConfig",
            fields=[
                (
                    "id",
                    short_stuff.django.models.ShortCodeField(
                        default=short_stuff.lib.gen_shortcode,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100)),
                ("secret", models.CharField(max_length=100)),
                (
                    "template_id",
                    models.CharField(blank=True, default="", max_length=25),
                ),
                (
                    "webhook_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=25
                    ),
                ),
                (
                    "active",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="serviceplan",
            name="paypal_invoicing",
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="stripe_token",
            new_name="paypal_token",
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=djmoney.models.fields.CurrencyField(
                blank=True, db_index=True, default="USD", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="paypal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="paypal",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether PayPal invoices are generated by default upon "
                "acceptance for non-shield orders. Ignored if there is not an active "
                "PaypalConfig.",
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="paypal_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="frozen_value",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Snapshotted amount after calculations have been completed "
                "and the relevant invoice is paid. This helps keep "
                "historical record in case the line item calculation "
                "algorithms change.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
