# Generated by Django 4.2.3 on 2023-08-09 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0179_deliverable_created_by_and_more"),
        ("sales", "0179_paypal_config"),
    ]

    operations = []
