# Generated by Django 4.2.3 on 2023-09-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0180_name_your_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details_template",
            field=models.CharField(
                default="",
                help_text="Prepopulate a template in the details field for "
                "a client to fill in.",
                max_length=500,
            ),
        ),
    ]
