# Generated by Django 4.2.3 on 2023-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0181_product_details_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="notes",
            field=models.TextField(blank=True, default="", max_length=5000),
        ),
    ]
