# Generated by Django 4.2.10 on 2024-03-06 21:39

import apps.sales.models
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import short_stuff.django.models
import short_stuff.lib


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0182_deliverable_notes_alter_lineitem_amount_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    short_stuff.django.models.ShortCodeField(
                        db_index=True,
                        default=short_stuff.lib.gen_shortcode,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_position",
                    models.FloatField(
                        db_index=True,
                        default=apps.sales.models.get_next_sample_position,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.product"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.submission",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="samples_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                through="sales.Sample",
                to="profiles.submission",
            ),
        ),
    ]
