# Generated by Django 4.2.10 on 2024-03-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0183_add_sample_leaf_table"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
