# Generated by Django 4.2.10 on 2024-03-06 22:03

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0184_migrate_samples"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="samples",
            new_name="samples_old",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="samples_new",
            new_name="samples",
        ),
    ]
