# Generated by Django 4.2.10 on 2024-03-07 01:08

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0185_shuffle_sample_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="samples_old",
        ),
    ]
