# Generated by Django 4.2.11 on 2024-04-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0186_remove_old_samples"),
    ]

    # Historical migration. Operation no longer needed.
    operations = []
