# Generated by Django 4.2.11 on 2024-05-20 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0189_create_shopping_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="created_on",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="created_on",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
