# Generated by Django 4.2.13 on 2024-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0190_alter_reference_created_on_alter_revision_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="auto_cancel_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
