# Generated by Django 5.0.9 on 2024-09-05 12:13

import django.utils.timezone
import short_stuff.django.models
import short_stuff.lib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0192_order_customer_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEventRecord",
            fields=[
                (
                    "id",
                    short_stuff.django.models.ShortCodeField(
                        default=short_stuff.lib.gen_shortcode,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(db_index=True, unique=True)),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
